version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  jaeger:
    image: jaegertracing/all-in-one:1.43
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"